sudo: false
dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.24.0
os:
  - linux
  - osx
cache: cargo
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - git submodule update --init --recursive

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
