sudo: false
dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - git submodule update --init --recursive
